[package]
name = "milo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.5.0"
clap = { version = "4.4.16", features = ["derive"] }
flate2 = "1.0.28"
tempfile = "3.9.0"
